### ISSUE TITLE
Update subscription parameters

### ISSUE THREAD

**Issue by nicooprat** [ccorcos/meteor-subs-cache#36]
Hi there!

Has anyone figured out a way to change a subscription parameters after a first init? Like working with pagination. For now, I'm overriding the subscription object in each autorun, causing templates to keep reference to previous object (that's how I understand the issue though) and not updating when the new subscription is created. 

My workaround is to create a reactiveVar 'ready' that I set to false every time I update parameters, and set to true in a sub.onReady() callback. Not very complicated, but I'd prefer a more clean way to manage it. 

Didn't find anything in docs, issues or in source code. Thanks :)

**Comment by satyavh** [comment]
I got the same issue. I tried different 'hacks' but in the end I unfortunately had to drop subs-cache for subscriptions that change params.

**Comment by jankapunkt** [comment]
It is because it creates the hash (for looking up the sub in the cache) by calling

```javascript
var hash = EJSON.stringify(withoutCallbacks(args));
if (hash in this.cache) {
    //... use cached sub
else
   //.... create new sub
```
Where `withoutCallbacks` removes callback arguments from args (which are all args of your subscription call), but not any other. 
This causes pattern like Template level subscriptions or filter tables to fail. The lookup can't find the "updated" subscription anymore since it generates a differnt hash.

@ccorcos @paranoico My suggestion: create hash solely based on the first arg (the subscription name) and let users handle their naming (convention > configuration).

If you like, I could implement this and update the tests.

Best Jan

**Comment by jankapunkt** [comment]
Please see PR #41

**Comment by paranoico** [comment]
Fix merged, thanks for testing @nicooprat
