### ISSUE TITLE
Subscriptions should always be stopped if the cacheLimit is reached

### ISSUE THREAD

**Issue by santiagopuentep** [ccorcos/meteor-subs-cache#59]
The subscriptions should be stopped when the cacheLimit is reached even if the expireAfter has not expired yet.

Without this it the cacheLimit is useless when the expireAfter is set to something other than -1 because the subscriptions keep pilling up indefinitely.

**Comment by paranoico** [comment]
Are you using the last version on atmosphere or the master branch?

**Comment by santiagopuentep** [comment]
I was using the version on atmosphere.

**Comment by jankapunkt** [comment]
Can you both please describe in detail how you expect this to be working correctly? 

-> Which subs are exactly stopped?
-> Which subs can remain running?

Should the behavior to determine which sub to stop rather be a stack-like or queue-like behavior  or something else and should users be able to configure this behavior?

With some information on that I can implemented a fix on this including some tests (which is why a good description of expected behavior will help a lot).

**Comment by paranoico** [comment]
We currently only use expireAfter value set to -1, so I can only elaborate the idea as far as I understand it:

- I think the subs that should be stopped must the the oldest ones. Not sure if there is some kind of timestamp on each subscription, but otherwise it could be some random manner to chose the subs to be stopped.

What do you think?

**Comment by jankapunkt** [comment]
I think there is currently the option to override the expiration on a subscription level so I think there needs to be a way to determine the candidate by oldest timestamp. If there are more than one sub than use the sub that has been added first. To determine the order of being added, each sub should receive an incrementing value like `index`.

I think randomness is something that willead to unpredictable behavior.

If there are more requirements please let me know.

**Comment by paranoico** [comment]
@jankapunkt I agree.

@santiagopuentep Santiago, what do you think?

**Comment by jankapunkt** [comment]
One more question that arises:

Should users be able to configure, whether to 

a) stop the oldest pub on limit reach

**Comment by paranoico** [comment]
Good points you have there, regarding each one:

a) If user can chose to not stop oldest subs on limit reach, then to me it is the same like setting expireAfter = -1, isn't it?

b) The only way app can decide when to stop sub is calling the stop method, otherwise how can the app make an automatic decision?

c) If sub is just rejected then it should behaviour like a normal Meteor subscription, to me it leaks to an unpredictable behaviour or at least a difficult one to debug, how can we avoid this? May be a master cached collection where last state of everyone is record, but anyway it could be hard to debug, isn't it?

**Comment by jankapunkt** [comment]
Okay so I checked the code again and the current behavior is currently

> delete the oldest subscription with count = 0 if the cache has overflown

So summarizing the debate, the code and @santiagopuentep issue I would go with the following:

- keep this as the default behavior (backward compatible)
- add a switch, that allows to define what happens on limit reach (configurable)
- keep this feature as lean as possible (maintainable)

I will propose a PR very soon so please let me know

**Comment by jankapunkt** [comment]
Okay please ignore my last comment and please test first my last PR #63 

I found that the measure to determine which sub to remove did not work when `count` is greater than zero. I used `startedAt` to find the "oldest" sub by date. Tests have been added. 

@santiagopuentep please check if this is fixing your issue.
